#!mainFile "main.opy"

#Activated extensions
#!extension explosionSounds
#!extension kineticExplosionEffects
#!extension playMoreEffects
#!extension spawnMoreDummyBots
#!extension projectiles

# for DVA's Slide ability
#!extension buffStatusEffects
#!extension buffAndDebuffSounds

# Juno hyper rift
#!extension energyExplosionEffects

# Bot Widowmaker scope
#!extension beamEffects

# for text color tags:
#!setupTags